[project]
name = "v2ray-auto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mshojaei77", email = "shojaeireal@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
v2ray-auto = "v2ray_auto:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
